apiVersion: v1
kind: PersistentVolume
metadata:
  name: capstone-web-pv
  namespace: capstone
spec:
  storageClassName: capstone-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/capstone_web"
  persistentVolumeReclaimPolicy: Retain
